services:
  mysql_db:
    image: mysql:latest
    container_name: lm_system_db
    environment:
      MYSQL_DATABASE: lm_system
      MYSQL_ROOT_PASSWORD: developmentPassword
  frontend:
    build:
      context: ./frontend
    container_name: lm_system_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build:
      context: .
    container_name: lm_system_backend
    ports:
      - "8000:8000"
    env_file:
      - .env.example
    depends_on:
      - mysql_db