services:
  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: lm_system
      MYSQL_ROOT_PASSWORD: developmentPassword
  frontend:
    build:
      context: ./frontend
    ports:
      - "3010:3000"
    depends_on:
      - backend
  backend:
    build:
      context: .
    env_file:
      - .env
    depends_on:
      - mysql_db